codecov:
  require_ci_to_pass: yes

ignore:
  - "exporters/otlp/internal/opentelemetry-proto-gen/**/*"
  - "exporters/trace/jaeger/internal/gen-go/**/*"

coverage:
  precision: 1
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
