apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      # Make sure to add the otlp receiver. 
      # This will use the default configuration, and open up the receiver on port 55680
      otlp: {}
    processors:
    extensions:
      health_check: {}
    exporters:
      jaeger:
        # Replace with a real endpoint.
        endpoint: "simplest-collector.default.svc.cluster.local:14250"
    service:
      extensions: [health_check]
      pipelines:
        traces/2:
          receivers: [otlp]
          processors: []
          exporters: [jaeger]